TEST_PROCEDURE(GS_GL20SC_PFO_S_ROBUSTNESS_TP_001, DEFAULT_TEST_RUN_TIME, "GL20SC_R", "PerFragmentOperations_R", "Scissor_R")
TEST_PROCEDURE(GS_GL20SC_PFO_BE_ROBUSTNESS_TP_001, DEFAULT_TEST_RUN_TIME, "GL20SC_R", "PerFragmentOperations_R", "BlendEquation_R")
TEST_PROCEDURE(GS_GL20SC_PFO_BF_ROBUSTNESS_TP_001, DEFAULT_TEST_RUN_TIME, "GL20SC_R", "PerFragmentOperations_R", "BlendFunc_R")
