#ifndef FRAMEBUFFER_TESTS_H
#define FRAMEBUFFER_TESTS_H

/* --------------- FramebufferTexture2D --------------- */
void GS_GL20SC_FO_FT2D_ROBUSTNESS_TP_001_init(void);
void GS_GL20SC_FO_FT2D_ROBUSTNESS_TP_001_draw(void);
void GS_GL20SC_FO_FT2D_ROBUSTNESS_TP_001_close(void);
void GS_GL20SC_FO_FT2D_ROBUSTNESS_TC_001();
void GS_GL20SC_FO_FT2D_ROBUSTNESS_TC_002();
void GS_GL20SC_FO_FT2D_ROBUSTNESS_TC_003();
void GS_GL20SC_FO_FT2D_ROBUSTNESS_TC_004();  /* It failed on Windows */
void GS_GL20SC_FO_FT2D_ROBUSTNESS_TC_005();
void GS_GL20SC_FO_FT2D_ROBUSTNESS_TC_006();
void GS_GL20SC_FO_FT2D_ROBUSTNESS_TC_007();
void GS_GL20SC_FO_FT2D_ROBUSTNESS_TC_008();
void GS_GL20SC_FO_FT2D_ROBUSTNESS_TC_009();
void GS_GL20SC_FO_FT2D_ROBUSTNESS_TC_010();  /* It failed on Windows */
void GS_GL20SC_FO_FT2D_ROBUSTNESS_TC_011();
void GS_GL20SC_FO_FT2D_ROBUSTNESS_TC_012();
void GS_GL20SC_FO_FT2D_ROBUSTNESS_TC_013();  /* It failed on Windows */

/* --------------- GetRenderbufferParameteriv --------------- */
void GS_GL20SC_FO_GRP_ROBUSTNESS_TP_001_init(void);
void GS_GL20SC_FO_GRP_ROBUSTNESS_TP_001_draw(void);
void GS_GL20SC_FO_GRP_ROBUSTNESS_TP_001_close(void);
void GS_GL20SC_FO_GRP_ROBUSTNESS_TC_001();
void GS_GL20SC_FO_GRP_ROBUSTNESS_TC_002();
void GS_GL20SC_FO_GRP_ROBUSTNESS_TC_003();
void GS_GL20SC_FO_GRP_ROBUSTNESS_TC_004();
void GS_GL20SC_FO_GRP_ROBUSTNESS_TC_005();
void GS_GL20SC_FO_GRP_ROBUSTNESS_TC_006();
void GS_GL20SC_FO_GRP_ROBUSTNESS_TC_007();
void GS_GL20SC_FO_GRP_ROBUSTNESS_TC_008();
void GS_GL20SC_FO_GRP_ROBUSTNESS_TC_009();  /* It crashed on Windows */
void GS_GL20SC_FO_GRP_ROBUSTNESS_TC_010();
void GS_GL20SC_FO_GRP_ROBUSTNESS_TC_011();

/* --------------- GetFramebufferAttachmentParameteriv --------------- */
void GS_GL20SC_FO_GFAP_ROBUSTNESS_TP_001_init(void);
void GS_GL20SC_FO_GFAP_ROBUSTNESS_TP_001_draw(void);
void GS_GL20SC_FO_GFAP_ROBUSTNESS_TP_001_close(void);
void GS_GL20SC_FO_GFAP_ROBUSTNESS_TC_001();
void GS_GL20SC_FO_GFAP_ROBUSTNESS_TC_002();
void GS_GL20SC_FO_GFAP_ROBUSTNESS_TC_003();
void GS_GL20SC_FO_GFAP_ROBUSTNESS_TC_004();
void GS_GL20SC_FO_GFAP_ROBUSTNESS_TC_005();
void GS_GL20SC_FO_GFAP_ROBUSTNESS_TC_006();
void GS_GL20SC_FO_GFAP_ROBUSTNESS_TC_007();
void GS_GL20SC_FO_GFAP_ROBUSTNESS_TC_008();  /* It crashed on Windows */
void GS_GL20SC_FO_GFAP_ROBUSTNESS_TC_009();
void GS_GL20SC_FO_GFAP_ROBUSTNESS_TC_010();
void GS_GL20SC_FO_GFAP_ROBUSTNESS_TC_011();
void GS_GL20SC_FO_GFAP_ROBUSTNESS_TC_012();
void GS_GL20SC_FO_GFAP_ROBUSTNESS_TC_013();  /* It failed on Windows */

/* --------------- CheckFramebufferStatus --------------- */
void GS_GL20SC_FO_CFS_ROBUSTNESS_TP_001_init(void);
void GS_GL20SC_FO_CFS_ROBUSTNESS_TP_001_draw(void);
void GS_GL20SC_FO_CFS_ROBUSTNESS_TP_001_close(void);
void GS_GL20SC_FO_CFS_ROBUSTNESS_TC_001();
void GS_GL20SC_FO_CFS_ROBUSTNESS_TC_002();
void GS_GL20SC_FO_CFS_ROBUSTNESS_TC_003();
void GS_GL20SC_FO_CFS_ROBUSTNESS_TC_004();
void GS_GL20SC_FO_CFS_ROBUSTNESS_TC_005();  /* It failed on Windows */
void GS_GL20SC_FO_CFS_ROBUSTNESS_TC_006();
void GS_GL20SC_FO_CFS_ROBUSTNESS_TC_007();
void GS_GL20SC_FO_CFS_ROBUSTNESS_TC_008();
void GS_GL20SC_FO_CFS_ROBUSTNESS_TC_009();

/* --------------- FramebufferRenderbuffer --------------- */
void GS_GL20SC_FO_FR_ROBUSTNESS_TP_001_init(void);
void GS_GL20SC_FO_FR_ROBUSTNESS_TP_001_draw(void);
void GS_GL20SC_FO_FR_ROBUSTNESS_TP_001_close(void);
void GS_GL20SC_FO_FR_ROBUSTNESS_TC_001();
void GS_GL20SC_FO_FR_ROBUSTNESS_TC_002();
void GS_GL20SC_FO_FR_ROBUSTNESS_TC_003();
void GS_GL20SC_FO_FR_ROBUSTNESS_TC_004();
void GS_GL20SC_FO_FR_ROBUSTNESS_TC_005();
void GS_GL20SC_FO_FR_ROBUSTNESS_TC_006();  /* It failed on Windows */
void GS_GL20SC_FO_FR_ROBUSTNESS_TC_007();  /* It failed on Windows */
void GS_GL20SC_FO_FR_ROBUSTNESS_TC_008();
void GS_GL20SC_FO_FR_ROBUSTNESS_TC_009();
void GS_GL20SC_FO_FR_ROBUSTNESS_TC_010();  /* It failed on Windows */

/* --------------- RenderbufferStorage --------------- */
void GS_GL20SC_FO_RS_ROBUSTNESS_TP_001_init(void);
void GS_GL20SC_FO_RS_ROBUSTNESS_TP_001_draw(void);
void GS_GL20SC_FO_RS_ROBUSTNESS_TP_001_close(void);
void GS_GL20SC_FO_RS_ROBUSTNESS_TC_001();
void GS_GL20SC_FO_RS_ROBUSTNESS_TC_002();
void GS_GL20SC_FO_RS_ROBUSTNESS_TC_003();
void GS_GL20SC_FO_RS_ROBUSTNESS_TC_004();
void GS_GL20SC_FO_RS_ROBUSTNESS_TC_005();
void GS_GL20SC_FO_RS_ROBUSTNESS_TC_006();
void GS_GL20SC_FO_RS_ROBUSTNESS_TC_007();  /* It failed on Windows */
void GS_GL20SC_FO_RS_ROBUSTNESS_TC_008();
void GS_GL20SC_FO_RS_ROBUSTNESS_TC_009();
void GS_GL20SC_FO_RS_ROBUSTNESS_TC_010();
void GS_GL20SC_FO_RS_ROBUSTNESS_TC_011();
void GS_GL20SC_FO_RS_ROBUSTNESS_TC_012();
void GS_GL20SC_FO_RS_ROBUSTNESS_TC_013();

/* --------------- GenRenderbuffers --------------- */
void GS_GL20SC_FO_GR_ROBUSTNESS_TP_001_init(void);
void GS_GL20SC_FO_GR_ROBUSTNESS_TP_001_draw(void);
void GS_GL20SC_FO_GR_ROBUSTNESS_TP_001_close(void);
void GS_GL20SC_FO_GR_ROBUSTNESS_TC_001();
void GS_GL20SC_FO_GR_ROBUSTNESS_TC_002();
void GS_GL20SC_FO_GR_ROBUSTNESS_TC_003(); /* It crashed on Windows */
void GS_GL20SC_FO_GR_ROBUSTNESS_TC_004();
void GS_GL20SC_FO_GR_ROBUSTNESS_TC_005();
void GS_GL20SC_FO_GR_ROBUSTNESS_TC_006();
void GS_GL20SC_FO_GR_ROBUSTNESS_TC_007(); /* It crashed on Windows */
void GS_GL20SC_FO_GR_ROBUSTNESS_TC_008();
void GS_GL20SC_FO_GR_ROBUSTNESS_TC_009();
void GS_GL20SC_FO_GR_ROBUSTNESS_TC_010();
void GS_GL20SC_FO_GR_ROBUSTNESS_TC_011();
void GS_GL20SC_FO_GR_ROBUSTNESS_TC_012();

/* --------------- BindRenderbuffer --------------- */  /* No crash */
void GS_GL20SC_FO_BR_ROBUSTNESS_TP_001_init(void);
void GS_GL20SC_FO_BR_ROBUSTNESS_TP_001_draw(void);
void GS_GL20SC_FO_BR_ROBUSTNESS_TP_001_close(void);
void GS_GL20SC_FO_BR_ROBUSTNESS_TC_001();
void GS_GL20SC_FO_BR_ROBUSTNESS_TC_002();
void GS_GL20SC_FO_BR_ROBUSTNESS_TC_003();
void GS_GL20SC_FO_BR_ROBUSTNESS_TC_004();
void GS_GL20SC_FO_BR_ROBUSTNESS_TC_005();
void GS_GL20SC_FO_BR_ROBUSTNESS_TC_006();
void GS_GL20SC_FO_BR_ROBUSTNESS_TC_007();
void GS_GL20SC_FO_BR_ROBUSTNESS_TC_008();
void GS_GL20SC_FO_BR_ROBUSTNESS_TC_009();
void GS_GL20SC_FO_BR_ROBUSTNESS_TC_010();

/* --------------- GenFramebuffer --------------- */
void GS_GL20SC_FO_GF_ROBUSTNESS_TP_001_init(void);
void GS_GL20SC_FO_GF_ROBUSTNESS_TP_001_draw(void);
void GS_GL20SC_FO_GF_ROBUSTNESS_TP_001_close(void);
void GS_GL20SC_FO_GF_ROBUSTNESS_TC_001();
void GS_GL20SC_FO_GF_ROBUSTNESS_TC_002();
void GS_GL20SC_FO_GF_ROBUSTNESS_TC_003();
void GS_GL20SC_FO_GF_ROBUSTNESS_TC_004();
void GS_GL20SC_FO_GF_ROBUSTNESS_TC_005(); /* It crashed on Windows */
void GS_GL20SC_FO_GF_ROBUSTNESS_TC_006();
void GS_GL20SC_FO_GF_ROBUSTNESS_TC_007();
void GS_GL20SC_FO_GF_ROBUSTNESS_TC_008(); /* It crashed the entire system on Windows */
void GS_GL20SC_FO_GF_ROBUSTNESS_TC_009(); /* It crashed and failed on Windows */
void GS_GL20SC_FO_GF_ROBUSTNESS_TC_010();
void GS_GL20SC_FO_GF_ROBUSTNESS_TC_011();
void GS_GL20SC_FO_GF_ROBUSTNESS_TC_012();
void GS_GL20SC_FO_GF_ROBUSTNESS_TC_013();
void GS_GL20SC_FO_GF_ROBUSTNESS_TC_014();
void GS_GL20SC_FO_GF_ROBUSTNESS_TC_015();

/* --------------- BindFramebuffer --------------- */ /* No crash */
void GS_GL20SC_FO_BF_ROBUSTNESS_TP_001_init(void);
void GS_GL20SC_FO_BF_ROBUSTNESS_TP_001_draw(void);
void GS_GL20SC_FO_BF_ROBUSTNESS_TP_001_close(void);
void GS_GL20SC_FO_BF_ROBUSTNESS_TC_001();
void GS_GL20SC_FO_BF_ROBUSTNESS_TC_002();
void GS_GL20SC_FO_BF_ROBUSTNESS_TC_003();
void GS_GL20SC_FO_BF_ROBUSTNESS_TC_004();
void GS_GL20SC_FO_BF_ROBUSTNESS_TC_005();
void GS_GL20SC_FO_BF_ROBUSTNESS_TC_006();
void GS_GL20SC_FO_BF_ROBUSTNESS_TC_007();
void GS_GL20SC_FO_BF_ROBUSTNESS_TC_008();
void GS_GL20SC_FO_BF_ROBUSTNESS_TC_009();
void GS_GL20SC_FO_BF_ROBUSTNESS_TC_010();
void GS_GL20SC_FO_BF_ROBUSTNESS_TC_011();


#endif