#ifndef TESTS_H
#define TESTS_H

/* --------------- BindBuffer --------------- */
void GS_GL20SC_BO_BB_ROBUSTNESS_TP_001_init(void);
void GS_GL20SC_BO_BB_ROBUSTNESS_TP_001_draw(void);
void GS_GL20SC_BO_BB_ROBUSTNESS_TP_001_close(void);
void GS_GL20SC_BO_BB_ROBUSTNESS_TC_001();
void GS_GL20SC_BO_BB_ROBUSTNESS_TC_002();
void GS_GL20SC_BO_BB_ROBUSTNESS_TC_003();
void GS_GL20SC_BO_BB_ROBUSTNESS_TC_004();
void GS_GL20SC_BO_BB_ROBUSTNESS_TC_005();
void GS_GL20SC_BO_BB_ROBUSTNESS_TC_006();
void GS_GL20SC_BO_BB_ROBUSTNESS_TC_007();
void GS_GL20SC_BO_BB_ROBUSTNESS_TC_008();
void GS_GL20SC_BO_BB_ROBUSTNESS_TC_009();
void GS_GL20SC_BO_BB_ROBUSTNESS_TC_010();
void GS_GL20SC_BO_BB_ROBUSTNESS_TC_011();

/* --------------- BufferData --------------- */
void GS_GL20SC_BO_BD_ROBUSTNESS_TP_001_init(void);
void GS_GL20SC_BO_BD_ROBUSTNESS_TP_001_draw(void);
void GS_GL20SC_BO_BD_ROBUSTNESS_TP_001_close(void);
void GS_GL20SC_BO_BD_ROBUSTNESS_TC_001();
void GS_GL20SC_BO_BD_ROBUSTNESS_TC_002();
void GS_GL20SC_BO_BD_ROBUSTNESS_TC_003();
void GS_GL20SC_BO_BD_ROBUSTNESS_TC_004();
void GS_GL20SC_BO_BD_ROBUSTNESS_TC_005();
void GS_GL20SC_BO_BD_ROBUSTNESS_TC_006(); // It crashed on Windows
void GS_GL20SC_BO_BD_ROBUSTNESS_TC_007();
void GS_GL20SC_BO_BD_ROBUSTNESS_TC_008(); // It failed on Windows
void GS_GL20SC_BO_BD_ROBUSTNESS_TC_009(); // It failed on Windows
void GS_GL20SC_BO_BD_ROBUSTNESS_TC_010();
void GS_GL20SC_BO_BD_ROBUSTNESS_TC_011();
void GS_GL20SC_BO_BD_ROBUSTNESS_TC_012();
void GS_GL20SC_BO_BD_ROBUSTNESS_TC_013();
void GS_GL20SC_BO_BD_ROBUSTNESS_TC_014(); // It failed on Windows

/* --------------- BufferSubData --------------- */
void GS_GL20SC_BO_BSD_ROBUSTNESS_TP_001_init(void);
void GS_GL20SC_BO_BSD_ROBUSTNESS_TP_001_draw(void);
void GS_GL20SC_BO_BSD_ROBUSTNESS_TP_001_close(void);
void GS_GL20SC_BO_BSD_ROBUSTNESS_TC_001();
void GS_GL20SC_BO_BSD_ROBUSTNESS_TC_002();
void GS_GL20SC_BO_BSD_ROBUSTNESS_TC_003();
void GS_GL20SC_BO_BSD_ROBUSTNESS_TC_004();
void GS_GL20SC_BO_BSD_ROBUSTNESS_TC_005();
void GS_GL20SC_BO_BSD_ROBUSTNESS_TC_006(); // It failed on Windows
void GS_GL20SC_BO_BSD_ROBUSTNESS_TC_007();
void GS_GL20SC_BO_BSD_ROBUSTNESS_TC_008();
void GS_GL20SC_BO_BSD_ROBUSTNESS_TC_009();
void GS_GL20SC_BO_BSD_ROBUSTNESS_TC_010();
void GS_GL20SC_BO_BSD_ROBUSTNESS_TC_011();
void GS_GL20SC_BO_BSD_ROBUSTNESS_TC_012(); // It crashed on Windows
void GS_GL20SC_BO_BSD_ROBUSTNESS_TC_013();
void GS_GL20SC_BO_BSD_ROBUSTNESS_TC_014();

/* --------------- GenBuffers --------------- */
void GS_GL20SC_BO_GB_ROBUSTNESS_TP_001_init(void);
void GS_GL20SC_BO_GB_ROBUSTNESS_TP_001_draw(void);
void GS_GL20SC_BO_GB_ROBUSTNESS_TP_001_close(void);
void GS_GL20SC_BO_GB_ROBUSTNESS_TC_001();
void GS_GL20SC_BO_GB_ROBUSTNESS_TC_002();
void GS_GL20SC_BO_GB_ROBUSTNESS_TC_003(); // It crashed on Windows
void GS_GL20SC_BO_GB_ROBUSTNESS_TC_004();
void GS_GL20SC_BO_GB_ROBUSTNESS_TC_005();
void GS_GL20SC_BO_GB_ROBUSTNESS_TC_006();
void GS_GL20SC_BO_GB_ROBUSTNESS_TC_007();
void GS_GL20SC_BO_GB_ROBUSTNESS_TC_008(); // It crashed on Windows

/* --------------- glGetBufferParameteriv --------------- */
void GS_GL20SC_BO_GBP_ROBUSTNESS_TP_001_init(void);
void GS_GL20SC_BO_GBP_ROBUSTNESS_TP_001_draw(void);
void GS_GL20SC_BO_GBP_ROBUSTNESS_TP_001_close(void);
void GS_GL20SC_BO_GBP_ROBUSTNESS_TC_001();
void GS_GL20SC_BO_GBP_ROBUSTNESS_TC_002();
void GS_GL20SC_BO_GBP_ROBUSTNESS_TC_003();
void GS_GL20SC_BO_GBP_ROBUSTNESS_TC_004();
void GS_GL20SC_BO_GBP_ROBUSTNESS_TC_005();
void GS_GL20SC_BO_GBP_ROBUSTNESS_TC_006();
void GS_GL20SC_BO_GBP_ROBUSTNESS_TC_007();
void GS_GL20SC_BO_GBP_ROBUSTNESS_TC_008(); // It crashed on Windows
void GS_GL20SC_BO_GBP_ROBUSTNESS_TC_009();
void GS_GL20SC_BO_GBP_ROBUSTNESS_TC_010();
void GS_GL20SC_BO_GBP_ROBUSTNESS_TC_011();
void GS_GL20SC_BO_GBP_ROBUSTNESS_TC_012();
void GS_GL20SC_BO_GBP_ROBUSTNESS_TC_013();
void GS_GL20SC_BO_GBP_ROBUSTNESS_TC_014();
void GS_GL20SC_BO_GBP_ROBUSTNESS_TC_015();

#endif